//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiLanguageApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguageApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly-typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        internal static string DateTimeFormatting {
            get {
                return ResourceManager.GetString("DateTimeFormatting", resourceCulture);
            }
        }
        
        internal static string NumberFormatting {
            get {
                return ResourceManager.GetString("NumberFormatting", resourceCulture);
            }
        }
        
        internal static string RegionalInformation {
            get {
                return ResourceManager.GetString("RegionalInformation", resourceCulture);
            }
        }
        
        internal static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        internal static string ShortDate {
            get {
                return ResourceManager.GetString("ShortDate", resourceCulture);
            }
        }
        
        internal static string LongDate {
            get {
                return ResourceManager.GetString("LongDate", resourceCulture);
            }
        }
        
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        internal static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        internal static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        internal static string NativeName {
            get {
                return ResourceManager.GetString("NativeName", resourceCulture);
            }
        }
        
        internal static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        internal static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        internal static string DecimalSeparator {
            get {
                return ResourceManager.GetString("DecimalSeparator", resourceCulture);
            }
        }
        
        internal static string ThousandsSeparator {
            get {
                return ResourceManager.GetString("ThousandsSeparator", resourceCulture);
            }
        }
        
        internal static string ShortDatePattern {
            get {
                return ResourceManager.GetString("ShortDatePattern", resourceCulture);
            }
        }
        
        internal static string LongDatePattern {
            get {
                return ResourceManager.GetString("LongDatePattern", resourceCulture);
            }
        }
        
        internal static string ShortTimePattern {
            get {
                return ResourceManager.GetString("ShortTimePattern", resourceCulture);
            }
        }
        
        internal static string LongTimePattern {
            get {
                return ResourceManager.GetString("LongTimePattern", resourceCulture);
            }
        }
        
        internal static string FirstDayOfWeek {
            get {
                return ResourceManager.GetString("FirstDayOfWeek", resourceCulture);
            }
        }
        
        internal static string IsRightToLeft {
            get {
                return ResourceManager.GetString("IsRightToLeft", resourceCulture);
            }
        }
    }
}
